version: "3.3"
networks:
  koala_network:

volumes:
  server_log_vol:


services:
  server-randomity-api:
    build: .
    networks:
      - koala_network
    image: server-randomity-api:latest
    volumes:
      - server_log_vol:/logs/
    ports:
      - "8080:8080"
    depends_on:
      - psql_db
    secrets:
      - user_ssh_key
  psql_db:
    networks:
      - koala_network
    container_name: psql_db
    expose:
      - 5432
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: gg
      POSTGRES_PASSWORD: Qwert123
  promtail:
    image: grafana/promtail:2.1.0
    container_name: monitoring-promtail
    volumes:
      - ./promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
      - server_log_vol:/var/log/
    command: "--config.file=/etc/promtail/docker-config.yaml"
secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa